---
networks:
  redis:
    name: redis
    driver: host
    external: true
  priv:
    name: priv
    driver: host
    external: true
  web:
    name: web
    driver: host
    external: true

services:
  webdesk:
    build: .
    image: webdesk:latest
    container_name: webdesk
    hostname: webdesk
    networks: [priv,web]
    expose:
      - 3000
    env_file:
      - .env
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:5432/${POSTGRES_DBNAME}
      PROXY_IP: ${PROXY_IP:?Set PROXY_IP}
      NODE_ENV: ${NODE_ENV:?Set NODE_ENV}
      DS_HOST: ${DS_HOST:?Set DS_HOST}
      THESVG_URL: ${THESVG_URL:?Set THESVG_URL}
      THESVG_REGISTRY: /data/icons.json
      FILES_DIR: /app/data/files
    command:
#     - --providers.docker.endpoint=tcp://socket-proxy:2375
#     - --providers.docker.exposedbydefault=false
    volumes:
      - ${DIR_PREFIX}/webdesk/data:/app/data
      - ${DIR_PREFIX}/webdesk/files:/app/files
      - ${DIR_PREFIX}/webdesk/icons:/app/public/icons
    restart: unless-stopped

